AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serialized Event Projector Lambda
Resources:
  EventProjectorLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: EventProjectorLambdaFunction
      Handler: io.serialized.samples.projector.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/event-projector-lambda-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        LambdaResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  EventProjectorLambdaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/project-event'
    Export:
      Name: EventProjectorLambdaApi
